name: end-to-end-ci

on: [push]

jobs:
  end-to-end-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure SSH
      run: |
        sudo apt install openssh-server
        sudo systemctl start sshd
        sudo ssh-keygen -t ed25519 -q -f /root/.ssh/id_ed25519 -N ""
        sudo bash -c "cat /root/.ssh/id_ed25519.pub > /root/.ssh/authorized_keys"
        sudo chmod 600 /root/.ssh/authorized_keys
        sudo ssh -o StrictHostKeyChecking=no localhost echo "password-less root login over ssh works"

    - name: Condition environment for Crucible
      run: |
        sudo mkdir -p /etc/sysconfig

    - name: Install crucible
      run: |
        sudo ./crucible-install.sh --no-client-server-registry --name nobody --email nobody@nobody.nobody.com --verbose

    - name: Crucible config check
      run: |
        sudo cat /etc/sysconfig/crucible

    - name: Crucible help
      run: |
        sudo crucible help

    - name: Crucible repo info
      run: |
        sudo crucible repo info

    - name: Crucible Run FIO
      run: |
        sudo crucible run fio --num-samples 3 --test-order r --mv-params ./tests/end-to-end/fio.json --endpoint remotehost,host:localhost,user:root,userenv:rhubi8,osruntime:podman,client:1

    - name: Crucible log info
      run: |
        sudo crucible log info

    - name: Crucible log view
      run: |
        sudo crucible log view
